import React from 'react';
export const matchingDetails = () => <div>matching distinct</div>;
export const matching_detail_0 = (p:any)=> <div>matching 0 Soundex</div>;
export const matching_detail_1 = (p:any)=> <div>matching 1 date proximity</div>;
export const matching_detail_2 = (p:any)=> <div>matching 2 probabilistic</div>;
export const matching_detail_3 = (p:any)=> <div>matching 3 threshold</div>;
export const matching_detail_4 = (p:any)=> <div>matching 4 Soundex</div>;
export const matching_detail_5 = (p:any)=> <div>matching 5 date proximity</div>;
export const matching_detail_6 = (p:any)=> <div>matching 6 probabilistic</div>;
export const matching_detail_7 = (p:any)=> <div>matching 7 threshold</div>;
export const matching_detail_8 = (p:any)=> <div>matching 8 Soundex</div>;
export const matching_detail_9 = (p:any)=> <div>matching 9 date proximity</div>;
export const matching_detail_10 = (p:any)=> <div>matching 10 probabilistic</div>;
export const matching_detail_11 = (p:any)=> <div>matching 11 threshold</div>;
export const matching_detail_12 = (p:any)=> <div>matching 12 Soundex</div>;
export const matching_detail_13 = (p:any)=> <div>matching 13 date proximity</div>;
export const matching_detail_14 = (p:any)=> <div>matching 14 probabilistic</div>;
export const matching_detail_15 = (p:any)=> <div>matching 15 threshold</div>;
export const matching_detail_16 = (p:any)=> <div>matching 16 Soundex</div>;
export const matching_detail_17 = (p:any)=> <div>matching 17 date proximity</div>;
export const matching_detail_18 = (p:any)=> <div>matching 18 probabilistic</div>;
export const matching_detail_19 = (p:any)=> <div>matching 19 threshold</div>;