import React from 'react';
export const ingestionDetails = () => <div>ingestion distinct</div>;
export const ingestion_detail_0 = (p:any)=> <div>ingestion 0 census</div>;
export const ingestion_detail_1 = (p:any)=> <div>ingestion 1 ship manifests</div>;
export const ingestion_detail_2 = (p:any)=> <div>ingestion 2 church registries</div>;
export const ingestion_detail_3 = (p:any)=> <div>ingestion 3 scanned</div>;
export const ingestion_detail_4 = (p:any)=> <div>ingestion 4 census</div>;
export const ingestion_detail_5 = (p:any)=> <div>ingestion 5 ship manifests</div>;
export const ingestion_detail_6 = (p:any)=> <div>ingestion 6 church registries</div>;
export const ingestion_detail_7 = (p:any)=> <div>ingestion 7 scanned</div>;
export const ingestion_detail_8 = (p:any)=> <div>ingestion 8 census</div>;
export const ingestion_detail_9 = (p:any)=> <div>ingestion 9 ship manifests</div>;
export const ingestion_detail_10 = (p:any)=> <div>ingestion 10 church registries</div>;
export const ingestion_detail_11 = (p:any)=> <div>ingestion 11 scanned</div>;
export const ingestion_detail_12 = (p:any)=> <div>ingestion 12 census</div>;
export const ingestion_detail_13 = (p:any)=> <div>ingestion 13 ship manifests</div>;
export const ingestion_detail_14 = (p:any)=> <div>ingestion 14 church registries</div>;
export const ingestion_detail_15 = (p:any)=> <div>ingestion 15 scanned</div>;
export const ingestion_detail_16 = (p:any)=> <div>ingestion 16 census</div>;
export const ingestion_detail_17 = (p:any)=> <div>ingestion 17 ship manifests</div>;
export const ingestion_detail_18 = (p:any)=> <div>ingestion 18 church registries</div>;
export const ingestion_detail_19 = (p:any)=> <div>ingestion 19 scanned</div>;