import React from 'react';
export const searchDetails = () => <div>search distinct</div>;
export const search_detail_0 = (p:any)=> <div>search 0 soundex</div>;
export const search_detail_1 = (p:any)=> <div>search 1 date range</div>;
export const search_detail_2 = (p:any)=> <div>search 2 place</div>;
export const search_detail_3 = (p:any)=> <div>search 3 name</div>;
export const search_detail_4 = (p:any)=> <div>search 4 soundex</div>;
export const search_detail_5 = (p:any)=> <div>search 5 date range</div>;
export const search_detail_6 = (p:any)=> <div>search 6 place</div>;
export const search_detail_7 = (p:any)=> <div>search 7 name</div>;
export const search_detail_8 = (p:any)=> <div>search 8 soundex</div>;
export const search_detail_9 = (p:any)=> <div>search 9 date range</div>;
export const search_detail_10 = (p:any)=> <div>search 10 place</div>;
export const search_detail_11 = (p:any)=> <div>search 11 name</div>;
export const search_detail_12 = (p:any)=> <div>search 12 soundex</div>;
export const search_detail_13 = (p:any)=> <div>search 13 date range</div>;
export const search_detail_14 = (p:any)=> <div>search 14 place</div>;
export const search_detail_15 = (p:any)=> <div>search 15 name</div>;
export const search_detail_16 = (p:any)=> <div>search 16 soundex</div>;
export const search_detail_17 = (p:any)=> <div>search 17 date range</div>;
export const search_detail_18 = (p:any)=> <div>search 18 place</div>;
export const search_detail_19 = (p:any)=> <div>search 19 name</div>;